version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db
    
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  tp-foyer:
    depends_on:
      - mysqldb
    image: arijhakouna/tpfoyer
    restart : always 
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://192.168.166.146:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root" ,
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",        
        "spring.jpa.hibernate.ddl-auto" : "update" }'
    stdin_open: true
    tty: true

volumes:
  db : 
